const GRAYSCALE_ACTION = 'GRAYSCALE_ACTION'
const ON_USERS_LOADED = 'ON_USERS_LOADED'
const GRAYSCALE_ACTION_NONE = 'GRAYSCALE_ACTION_NONE'

export {
    GRAYSCALE_ACTION,
    ON_USERS_LOADED,
    GRAYSCALE_ACTION_NONE
}