export const START_PRODUCTS_LOADING = 'START_PRODUCTS_LOADING';
export const END_PRODUCTS_LOADING = 'END_PRODUCTS_LOADING';
export const SET_PRODUCTS = 'SET_PRODUCTS';
export const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_WISHLIST = 'REMOVE_WISHLIST';
export const REMOVE_CART = 'REMOVE_CART';
export const ERROR = 'ERROR';
