const START_PRODUCTS_LOADING = 'START_PRODUCTS_LOADING'
const END_PRODUCTS_LOADING = 'END_PRODUCTS_LOADING'
const SET_PRODUCTS = 'SET_PRODUCTS'
const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST'
const ADD_TO_CART = 'ADD_TO_CART'
const REMOVE_WISHLIST = 'REMOVE_WISHLIST'
const REMOVE_CART = 'REMOVE_CART'



export {
    START_PRODUCTS_LOADING,
    END_PRODUCTS_LOADING,
    SET_PRODUCTS,
    ADD_TO_WISHLIST,
    ADD_TO_CART,
    REMOVE_WISHLIST,
    REMOVE_CART
}