const GET_CATEGORY = 'GET_CATEGORY'
const ADD_PRODUCT_ID = 'ADD_PRODUCT_ID'
const UPDATE_PRODUCT = 'UPDATE_PRODUCT'
const HANDLE_ITEM_CHANGE = 'HANDLE_ITEM_CHANGE'
const CLEAR_INPUT = 'CLEAR_INPUT'
const CHANGE_INPUT_ERROR = 'CHANGE_INPUT_ERROR'
const OPEN_MODAL = 'OPEN_MODAL'


export {
    GET_CATEGORY,
    ADD_PRODUCT_ID,
    UPDATE_PRODUCT,
    HANDLE_ITEM_CHANGE,
    CHANGE_INPUT_ERROR,
    CLEAR_INPUT,
    OPEN_MODAL
}